image: maven:latest

stages:
  - build
  - test
  - deploy

services:
  - postgres:12.2-alpine

variables:
  POSTGRES_DB: $POSTGRES_DB
  POSTGRES_USER: $POSTGRES_USER
  POSTGRES_PASSWORD: $POSTGRES_PASSWORD
  POSTGRES_HOST_AUTH_METHOD: $POSTGRES_HOST_AUTH_METHOD
  HOST_USER_NAME: $HOST_USER_NAME
  HOST_PASSWORD: $HOST_PASSWORD
  HOST_URL: $HOST_URL

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn compile
  only:
    - merge_requests

test:
  stage: test
  script:
    - mvn test
  only:
    - merge_requests

deploy:
  stage: deploy
  script:
    - git push https://$HOST_USER_NAME:$HOST_PASSWORD@$HOST_URL stage
  only:
    - stage