image: java:latest

stages:
    - build


build:
    stage: build
    script: src/main/java/ru/skillbox/socialnetwork SocialNetworkApplication.java
    artifacts:
        paths:
            - SocialNetworkApplication.*

